/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author luis.santos6
 */
public class Categorias extends javax.swing.JFrame {

    /**
     * Creates new form Categorias
     */
    public Categorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCategorias = new javax.swing.JLabel();
        btnRomance = new javax.swing.JButton();
        btnFantasia = new javax.swing.JButton();
        btnTerror = new javax.swing.JButton();
        btnSuspense = new javax.swing.JButton();
        btnPsicologia = new javax.swing.JButton();
        btnHumor = new javax.swing.JButton();
        btnDidatico = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        labelCategorias.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        labelCategorias.setForeground(new java.awt.Color(255, 255, 255));
        labelCategorias.setText("Categorias");

        btnRomance.setBackground(new java.awt.Color(204, 153, 255));
        btnRomance.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnRomance.setForeground(new java.awt.Color(255, 255, 255));
        btnRomance.setText("Romance");
        btnRomance.setBorder(null);

        btnFantasia.setBackground(new java.awt.Color(204, 153, 255));
        btnFantasia.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnFantasia.setForeground(new java.awt.Color(255, 255, 255));
        btnFantasia.setText("Fantasia");
        btnFantasia.setBorder(null);
        btnFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFantasiaActionPerformed(evt);
            }
        });

        btnTerror.setBackground(new java.awt.Color(204, 153, 255));
        btnTerror.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnTerror.setForeground(new java.awt.Color(255, 255, 255));
        btnTerror.setText("Terror");
        btnTerror.setBorder(null);

        btnSuspense.setBackground(new java.awt.Color(204, 153, 255));
        btnSuspense.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSuspense.setForeground(new java.awt.Color(255, 255, 255));
        btnSuspense.setText("Suspense");
        btnSuspense.setBorder(null);

        btnPsicologia.setBackground(new java.awt.Color(204, 153, 255));
        btnPsicologia.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPsicologia.setForeground(new java.awt.Color(255, 255, 255));
        btnPsicologia.setText("Psicológia");
        btnPsicologia.setBorder(null);

        btnHumor.setBackground(new java.awt.Color(204, 153, 255));
        btnHumor.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnHumor.setForeground(new java.awt.Color(255, 255, 255));
        btnHumor.setText("Humor");
        btnHumor.setBorder(null);

        btnDidatico.setBackground(new java.awt.Color(204, 153, 255));
        btnDidatico.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnDidatico.setForeground(new java.awt.Color(255, 255, 255));
        btnDidatico.setText("Didatico");
        btnDidatico.setBorder(null);

        btnVoltar.setBackground(new java.awt.Color(204, 153, 255));
        btnVoltar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("< ");
        btnVoltar.setBorder(null);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(labelCategorias)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addComponent(btnRomance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTerror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSuspense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPsicologia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHumor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDidatico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(18, 18, 18)
                .addComponent(labelCategorias)
                .addGap(28, 28, 28)
                .addComponent(btnRomance)
                .addGap(18, 18, 18)
                .addComponent(btnFantasia)
                .addGap(18, 18, 18)
                .addComponent(btnTerror)
                .addGap(18, 18, 18)
                .addComponent(btnSuspense)
                .addGap(18, 18, 18)
                .addComponent(btnPsicologia)
                .addGap(18, 18, 18)
                .addComponent(btnHumor)
                .addGap(18, 18, 18)
                .addComponent(btnDidatico)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFantasiaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDidatico;
    private javax.swing.JButton btnFantasia;
    private javax.swing.JButton btnHumor;
    private javax.swing.JButton btnPsicologia;
    private javax.swing.JButton btnRomance;
    private javax.swing.JButton btnSuspense;
    private javax.swing.JButton btnTerror;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCategorias;
    // End of variables declaration//GEN-END:variables
}
