/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author luis.santos6
 */
public class categorias extends javax.swing.JFrame {

    /**
     * Creates new form Categorias
     */
    public categorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCadastroDoLivro = new javax.swing.JLabel();
        jButtonRomance = new javax.swing.JButton();
        jButtonFantasia = new javax.swing.JButton();
        jButtonTerror = new javax.swing.JButton();
        jButtonSuspense = new javax.swing.JButton();
        jButtonPsicologia = new javax.swing.JButton();
        jButtonHumor = new javax.swing.JButton();
        jButtonDidatico = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        jLabelCadastroDoLivro.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabelCadastroDoLivro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadastroDoLivro.setText("Categorias");

        jButtonRomance.setBackground(new java.awt.Color(204, 153, 255));
        jButtonRomance.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonRomance.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRomance.setText("Romance");
        jButtonRomance.setBorder(null);

        jButtonFantasia.setBackground(new java.awt.Color(204, 153, 255));
        jButtonFantasia.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonFantasia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFantasia.setText("Fantasia");
        jButtonFantasia.setBorder(null);
        jButtonFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFantasiaActionPerformed(evt);
            }
        });

        jButtonTerror.setBackground(new java.awt.Color(204, 153, 255));
        jButtonTerror.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonTerror.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTerror.setText("Terror");
        jButtonTerror.setBorder(null);

        jButtonSuspense.setBackground(new java.awt.Color(204, 153, 255));
        jButtonSuspense.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonSuspense.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSuspense.setText("Suspense");
        jButtonSuspense.setBorder(null);

        jButtonPsicologia.setBackground(new java.awt.Color(204, 153, 255));
        jButtonPsicologia.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonPsicologia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPsicologia.setText("Psicológia");
        jButtonPsicologia.setBorder(null);

        jButtonHumor.setBackground(new java.awt.Color(204, 153, 255));
        jButtonHumor.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonHumor.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHumor.setText("Humor");
        jButtonHumor.setBorder(null);

        jButtonDidatico.setBackground(new java.awt.Color(204, 153, 255));
        jButtonDidatico.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonDidatico.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDidatico.setText("Didatico");
        jButtonDidatico.setBorder(null);

        jButton8.setBackground(new java.awt.Color(204, 153, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("< ");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRomance)
                            .addComponent(jButtonFantasia)
                            .addComponent(jButtonTerror)
                            .addComponent(jButtonSuspense)
                            .addComponent(jButtonPsicologia)
                            .addComponent(jButtonHumor)
                            .addComponent(jButtonDidatico)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelCadastroDoLivro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton8)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jLabelCadastroDoLivro)
                .addGap(29, 29, 29)
                .addComponent(jButtonRomance)
                .addGap(18, 18, 18)
                .addComponent(jButtonFantasia)
                .addGap(18, 18, 18)
                .addComponent(jButtonTerror)
                .addGap(18, 18, 18)
                .addComponent(jButtonSuspense)
                .addGap(18, 18, 18)
                .addComponent(jButtonPsicologia)
                .addGap(18, 18, 18)
                .addComponent(jButtonHumor)
                .addGap(18, 18, 18)
                .addComponent(jButtonDidatico)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFantasiaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new categorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonDidatico;
    private javax.swing.JButton jButtonFantasia;
    private javax.swing.JButton jButtonHumor;
    private javax.swing.JButton jButtonPsicologia;
    private javax.swing.JButton jButtonRomance;
    private javax.swing.JButton jButtonSuspense;
    private javax.swing.JButton jButtonTerror;
    private javax.swing.JLabel jLabelCadastroDoLivro;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
